### ISSUE TITLE
feature request: use the `options` from action-table-filter-menu for the sort order on that column

### ISSUE THREAD

**Issue by benishs** [colinaut/action-table#6]
Perhaps related to [#5](https://github.com/colinaut/action-table/issues/5), since it has to do with the order of items in the filter drop down: another one of my columns is a classification (for high school football), which is based on the size of the school. In this particular case, the classifications ordered largest to smallest looks like this:
5A
4A
3A
2A
1A
8 man
6 man

As you can see, there is no standard sort order for those that will put those in the correct order based on the size of the classification. I'd love a way to be able to manually the define the order of that drop down to mirror the classification size ordering.

In this example, the number of classifications are relatively small and I'll know what they are ahead of time so I can include them all in `<action-table-filter-menu>` – but I imagine any method to reorder the options in that filter drop down would require some sort of fallback in case it encounters a value in the data that is not in the manual sort order list. Perhaps: use the manually defined values in the given order first, then those list any values not manually specified.

That brings up the question of what should happen if my other idea for a reverse/descending sort order ([#5](https://github.com/colinaut/action-table/issues/5)) is combined with this manual sort order idea… I'd say the manually defined order should always be used in the exact order provided, and only the fallback (any items not explicitly defined in the sort order attribute) should be affected by the reverse/descending attribute. Because if you want those manually defined sort order items in a reverse order you could just enter them in that reverse order to begin with.

Related: it'd be great to also be able to use this manually defined order from the filter menu as the sort order on the table. I know that I could accomplish this by adding a `data-sort` attribute on the `td`s to override the sort order, but then I'm adding `data-sort` attributes to thousands of `td`s. I could certainly automate that, but it seems like a lot of redundant data to include –especially if I'm already defining the sort order I want in the filter.

**Comment by benishs** [comment]
Shoot. I just finished reading the documentation and realized that this feature already largely exists:
> options - (optional) to override the generated menu add a list of options as a comma delimited string

e.g. 
`<action-table-filter-menu name="Class" options="5A,4A,3A,2A,1A,8man,6man">`
https://go.benish.io/RHDwN3jh

Apologies for missing that – I thought I had read all of the Readme before opening this Issue, but must've got distracted.

So I guess the answer to: what to do if there is data not manually defined is: ignore it in that filter menu. Which seems like a good answer to me (I can see how it'd be useful to omit some values).

I suppose the part of this request that is still valid is the last bit: it'd be nice to be able to use the order I define in `options` as the sort order on that column of data, so I don't have to add thousands of `data-sort` attributes – but I can certainly do that if need be.

**Comment by colinaut** [comment]
Yep I added the options attribute as an escape hatch for exactly needs like yours. As for the sort order for the table itself, the data-sort is that same escape hatch. 

The action-table-filter-menu element is not in any way attached to the sorting. How it works in general is creates the options (or uses the ones provided). Then it sends a custom event on change with the filter choice to that the action-table listens for. Adding a means for it to also read those options on the action-table-filter-menu element would be cumbersome and not really in keeping with component style of code as it would tie them together too strongly.

The only thing I can think of that skips the data-sort on tds would be adding a data sort attribute on th with a comma separated list. Reading that attribute is easy. Making it sort that way is harder since I'd need to rewire how sort works from the basic alphanumeric way it is now to some weird custom thing where "6 man" = 1, "8 man" = 2, "1A" = 3, etc.. I can see that this is potentially useful in some situations.

I'll add it as an enhancement request and think on it but I can't guarantee implementing it.

**Comment by colinaut** [comment]
Thinking out loud on this… I could likely grab said proposed comma separated data sort attribute on the th; then turn it into an array and use indexOf for the sort ordering. This would turn the values into numbers. As a fallback, anything that doesn't match would then just be alphanumeric sorted as per norm. I could implement this in the sortTable() function or in the getTableContent() which stores the values for later sorting/filtering.

Possibly doable without adding much code. I'll think on it more.

**Comment by colinaut** [comment]
Added with release 2.4.2. New comma separated string attribute data-order on the th. See README or [release notes](https://github.com/colinaut/action-table/releases/tag/2.4.2). I've also included it's use in the [demo](https://colinaut.github.io/action-table/)

**Comment by benishs** [comment]
I love it! `data-order` on the `th` seems like a great way to deal with this, and your example of sorting months chronologically is a great example of how this could be useful to others. Thanks again!
